(このファイルは Makefile の説明)

※Makefile には，Shift_JISの日本語を書かないこと．

冒頭の部分は，必要な設定の記述． 講義資料のMakefileの雛形と概ね同様．

後半の部分に書かれているように，3つのターゲットを Makefile に追加する．

---
.SUFFIXES: .java .class

JAVAC	= javac
JAVA	= java

SRC	= $(wildcard *.java)
CLASS	= $(SRC:.java=.class)
PROGRAM	= $(shell pwd)

all: $(CLASS)

test:;
	@echo 今回は make test は使用できません
	@echo kada1から3をターゲットとする規則を追加してください
	@echo make kadai1と入力すれば./kadai1.shを実行する

# make kadai1の規則を追加する

# make kadai2の規則を追加する
	
# make kadai3の規則を追加する

.java.class:
	$(JAVAC) $<

clean:;	\rm -f *.class
---

